name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2 
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: zephyrprojectworkspace

      - name: Initialize
        working-directory: zephyrprojectworkspace
        run: |
          west init -l .
          west update

      - name: Build Firmware
        working-directory: zephyrprojectworkspace/example-app-microchip-vscode.git
        run: |
          cmake app -DCMAKE_BUILD_TYPE=Release --preset=atsame54_xpro
          cmake --build app/build

      #- name: Build Firmware Tests 
      #  working-directory: example-application
      #  run: |
      #    west twister -T app -v --inline-logs --integration

      #- name: Twister Tests
      #  working-directory: example-application
      #  run: |
      #    west twister -T tests --integration
